import 'dart:async';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:image/image.dart' as img;
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../../core/utils/file_utils.dart';
import '../../../core/utils/proof_reference_label.dart';
import '../../../l10n/app_localizations.dart';
import '../domain/proof.dart';
import '../domain/proof_local_image.dart';
import '../presentation/proof_category_asset.dart';

/// Variante de mise en page unitaire (réglage « Style de rapport »).
enum PdfReportStyle { standard, premium }

/// Options d’apparence PDF (réglages + export).
@immutable
class PdfAppearancePreferences {
  final bool showBranding;
  final bool showCredibilityBlock;
  final bool showDetailedLocation;
  final bool includeAllPhotos;
  final PdfReportStyle reportStyle;

  const PdfAppearancePreferences({
    this.showBranding = true,
    this.showCredibilityBlock = true,
    this.showDetailedLocation = true,
    this.includeAllPhotos = true,
    this.reportStyle = PdfReportStyle.standard,
  });

  static const PdfAppearancePreferences defaults = PdfAppearancePreferences();
}

/// Filtre métadonnées sensibles dans le rapport (selon préférences).
@immutable
class PdfMetadataExportMask {
  final bool includeClient;
  final bool includeSite;
  final bool includeNote;

  const PdfMetadataExportMask({
    this.includeClient = true,
    this.includeSite = true,
    this.includeNote = true,
  });

  static const PdfMetadataExportMask all = PdfMetadataExportMask();
}

class ProofPdfLabels {
  final String docTitle;
  final String typeLabel;
  final String typeValue;
  final String dateLabel;
  final String dateValue;
  final String timeLabel;
  final String timeValue;
  final String addressLabel;
  final String addressValue;
  final String coordinatesLabel;
  final String coordinatesValue;
  final String contextLabel;
  final String contextValue;
  final String noteLabel;
  final String noteValue;
  final String brandFooter;

  // Premium report fields
  final String subtitle;
  final String proofSummaryTitle;
  final String photoSectionTitle;
  final String photoSectionTitlePlural;
  final String locationSectionTitle;
  final String observationsTitle;
  final String traceabilityTitle;
  final String noObservationText;
  final String capturedOnLabel;
  final String exportedOnLabel;
  final String geoRecordedLabel;
  final String addressResolvedLabel;
  final String referenceLabel;
  final String sourceLabel;
  final String sourceValue;
  final String clientLabel;
  final String clientValue;
  final String siteMissionLabel;
  final String siteMissionValue;
  final String yesText;
  final String noText;
  final String generatedByText;
  final String fieldProofDocText;
  final String autoGeneratedText;

  /// Fin de document (synthèse utile)
  final String documentSummaryTitle;
  final String dataIncludedDescription;
  final String documentScopeNote;
  final String photosInExportLabel;

  const ProofPdfLabels({
    required this.docTitle,
    required this.typeLabel,
    required this.typeValue,
    required this.dateLabel,
    required this.dateValue,
    required this.timeLabel,
    required this.timeValue,
    required this.addressLabel,
    required this.addressValue,
    required this.coordinatesLabel,
    required this.coordinatesValue,
    required this.contextLabel,
    required this.contextValue,
    required this.noteLabel,
    required this.noteValue,
    required this.brandFooter,
    required this.subtitle,
    required this.proofSummaryTitle,
    required this.photoSectionTitle,
    required this.photoSectionTitlePlural,
    required this.locationSectionTitle,
    required this.observationsTitle,
    required this.traceabilityTitle,
    required this.noObservationText,
    required this.capturedOnLabel,
    required this.exportedOnLabel,
    required this.geoRecordedLabel,
    required this.addressResolvedLabel,
    required this.referenceLabel,
    required this.sourceLabel,
    required this.sourceValue,
    required this.clientLabel,
    required this.clientValue,
    required this.siteMissionLabel,
    required this.siteMissionValue,
    required this.yesText,
    required this.noText,
    required this.generatedByText,
    required this.fieldProofDocText,
    required this.autoGeneratedText,
    required this.documentSummaryTitle,
    required this.dataIncludedDescription,
    required this.documentScopeNote,
    required this.photosInExportLabel,
  });

  static ProofPdfLabels fromProof({
    required Proof proof,
    required AppLocalizations l10n,
    String? clientName,
    String? siteName,
  }) {
    final contextValue = (clientName != null)
        ? (siteName != null ? '$clientName - $siteName' : clientName)
        : l10n.unclassified;
    final coords = proof.latitude != null && proof.longitude != null
        ? '${proof.latitude!.toStringAsFixed(5)}, ${proof.longitude!.toStringAsFixed(5)}'
        : l10n.coordinatesUnavailable;
    final typeValue = switch (proof.proofType) {
      ProofType.inspection => l10n.proofTypeInspection,
      ProofType.delivery => l10n.proofTypeDelivery,
      ProofType.workProgress => l10n.proofTypeWorkProgress,
      ProofType.incident => l10n.proofTypeIncident,
      ProofType.inventory => l10n.proofTypeInventory,
      ProofType.other => l10n.proofTypeOther,
    };
    return ProofPdfLabels(
      docTitle: proof.title,
      typeLabel: l10n.proofType,
      typeValue: typeValue,
      dateLabel: l10n.date,
      dateValue: proof.overlayDateText,
      timeLabel: l10n.time,
      timeValue: proof.overlayTimeText,
      addressLabel: l10n.address,
      addressValue: proof.address ??
          proof.overlayAddressText ??
          l10n.addressUnavailable,
      coordinatesLabel: l10n.coordinates,
      coordinatesValue: coords,
      contextLabel: l10n.proofContext,
      contextValue: contextValue,
      noteLabel: l10n.note,
      noteValue: (proof.description != null && proof.description!.isNotEmpty)
          ? proof.description!
          : l10n.noNote,
      brandFooter: 'StampSight - ${l10n.libraryTitle}',
      subtitle: l10n.pdfSubtitle,
      proofSummaryTitle: l10n.pdfProofSummary,
      photoSectionTitle: l10n.pdfPhotographicEvidence,
      photoSectionTitlePlural: l10n.pdfPhotographicEvidencePlural,
      locationSectionTitle: l10n.pdfLocationSection,
      observationsTitle: l10n.pdfObservations,
      traceabilityTitle: l10n.pdfTraceability,
      noObservationText: l10n.pdfNoObservation,
      capturedOnLabel: l10n.pdfCapturedOn,
      exportedOnLabel: l10n.pdfExportedOn,
      geoRecordedLabel: l10n.pdfGeoRecorded,
      addressResolvedLabel: l10n.pdfAddressResolved,
      referenceLabel: l10n.pdfReference,
      sourceLabel: l10n.source,
      sourceValue: l10n.sourceLocal,
      clientLabel: l10n.pdfClient,
      clientValue: clientName ?? '-',
      siteMissionLabel: l10n.pdfSiteMission,
      siteMissionValue: siteName ?? '-',
      yesText: l10n.pdfYes,
      noText: l10n.pdfNo,
      generatedByText: l10n.pdfGeneratedBy,
      fieldProofDocText: l10n.pdfFieldProofDoc,
      autoGeneratedText: l10n.pdfAutoGenerated,
      documentSummaryTitle: l10n.pdfDocumentSummaryTitle,
      dataIncludedDescription: l10n.pdfDataIncludedDescription,
      documentScopeNote: l10n.pdfDocumentScopeNote,
      photosInExportLabel: l10n.pdfPhotosInExport,
    );
  }
}

abstract final class ProofExportService {
  static final Map<String, Future<File>> _writePdfTempInFlight = {};

  static const String _pdfFontAsset = 'assets/fonts/Roboto-VF.ttf';

  static pw.Font? _pdfUnicodeFont;

  static String _pdfSafeText(String value) {
    return value
        .replaceAll('\u2014', '-')
        .replaceAll('\u2013', '-')
        .replaceAll('\u2212', '-')
        .replaceAll('\u00A0', ' ')
        .replaceAll('\u202F', ' ')
        .replaceAll('\u00AB', '"')
        .replaceAll('\u00BB', '"')
        .replaceAll('\u2018', "'")
        .replaceAll('\u2019', "'")
        .replaceAll('\u201C', '"')
        .replaceAll('\u201D', '"');
  }

  static Future<pw.Font> _loadPdfUnicodeFont() async {
    if (_pdfUnicodeFont != null) return _pdfUnicodeFont!;
    final data = await rootBundle.load(_pdfFontAsset);
    _pdfUnicodeFont = pw.Font.ttf(data);
    return _pdfUnicodeFont!;
  }

  static const int _pdfImageMaxDim = 800;

  static img.Image _resizeForPdf(img.Image src) {
    if (src.width <= _pdfImageMaxDim && src.height <= _pdfImageMaxDim) {
      return src;
    }
    final landscape = src.width >= src.height;
    return img.copyResize(
      src,
      width: landscape ? _pdfImageMaxDim : null,
      height: landscape ? null : _pdfImageMaxDim,
      interpolation: img.Interpolation.average,
    );
  }

  static String _safeSlug(String raw, {int maxLen = 48}) {
    final s = raw
        .replaceAll(RegExp(r'[^\w\s\-]'), '')
        .replaceAll(RegExp(r'\s+'), '_')
        .trim();
    if (s.isEmpty) return 'preuve';
    return s.length > maxLen ? s.substring(0, maxLen) : s;
  }

  static Future<File> prepareShareableImageFile(Proof proof) async {
    if (proof.refersToLocalImageFile) {
      return File(proof.imagePath);
    }
    final assetPath = ProofCategoryAsset.placeholderFor(proof.proofType);
    ByteData data;
    try {
      data = await rootBundle.load(assetPath);
    } catch (_) {
      data = await rootBundle.load(ProofCategoryAsset.homeMirrorFor(proof.proofType));
    }
    final dir = await getTemporaryDirectory();
    final slug = _safeSlug(proof.title);
    final file = File('${dir.path}/stampsight_${proof.id}_$slug.webp');
    await file.writeAsBytes(data.buffer.asUint8List());
    return file;
  }

  static Future<File> saveImageToExports(Proof proof) async {
    final tmp = await prepareShareableImageFile(proof);
    final exports = await FileUtils.exportsDirectoryPath;
    final slug = _safeSlug(proof.title);
    final ext =
        p.extension(tmp.path).isNotEmpty ? p.extension(tmp.path) : '.jpg';
    final dest = File('$exports/stampsight_${proof.id}_$slug$ext');
    await tmp.copy(dest.path);
    return dest;
  }

  static Future<Uint8List?> _assetAsPngBytes(String assetPath) async {
    try {
      final data = await rootBundle.load(assetPath);
      final decoded = img.decodeImage(data.buffer.asUint8List());
      if (decoded == null) return null;
      return Uint8List.fromList(img.encodePng(decoded));
    } catch (_) {
      return null;
    }
  }

  static String _fmtDt(DateTime dt) {
    String p2(int v) => v.toString().padLeft(2, '0');
    return '${p2(dt.day)}/${p2(dt.month)}/${dt.year}  ${p2(dt.hour)}:${p2(dt.minute)}';
  }

  // ---------------------------------------------------------------------------
  // PDF brand palette (mirrors AppColors for the pdf package)
  // ---------------------------------------------------------------------------
  static final _bleuNuit = PdfColor.fromInt(0xFF0D1B2A);
  static final _grisFonce = PdfColor.fromInt(0xFF1E293B);
  static final _grisLabel = PdfColor.fromInt(0xFF64748B);
  static final _grisClair = PdfColor.fromInt(0xFF94A3B8);
  static final _separateur = PdfColor.fromInt(0xFFE2E8F0);
  static final _fondClair = PdfColor.fromInt(0xFFF8FAFC);

  // ---------------------------------------------------------------------------
  // V3 Premium PDF builder
  // ---------------------------------------------------------------------------
  static Future<Uint8List?> _loadImageAsPng(String filePath) async {
    try {
      final f = File(filePath);
      if (!f.existsSync()) return null;
      final bytes = await f.readAsBytes();
      final decoded = img.decodeImage(bytes);
      if (decoded == null) return null;
      final resized = _resizeForPdf(decoded);
      return Uint8List.fromList(img.encodePng(resized));
    } catch (_) {
      return null;
    }
  }

  static Future<Uint8List> buildPdfBytes(
    Proof proof,
    ProofPdfLabels labels, {
    PdfAppearancePreferences appearance = PdfAppearancePreferences.defaults,
    PdfMetadataExportMask metadataMask = PdfMetadataExportMask.all,
  }) async {
    final font = await _loadPdfUnicodeFont();
    String t(String s) => _pdfSafeText(s);

    // ----- Load proof image (unchanged logic) -----
    Uint8List? png;
    if (proof.refersToLocalImageFile) {
      png = await _loadImageAsPng(proof.imagePath);
    }
    if (png == null) {
      for (final path in [
        ProofCategoryAsset.placeholderFor(proof.proofType),
        ProofCategoryAsset.homeMirrorFor(proof.proofType),
        ProofCategoryAsset.genericProofs,
      ]) {
        png = await _assetAsPngBytes(path);
        if (png != null) break;
      }
    }

    // ----- Load additional images -----
    final List<Uint8List> additionalPngs = [];
    for (final extraPath in proof.additionalImagePaths) {
      final extra = await _loadImageAsPng(extraPath);
      if (extra != null) additionalPngs.add(extra);
    }

    // ----- Computed data -----
    final now = DateTime.now();
    final exportDate = _fmtDt(now);
    final capturedDate = '${t(labels.dateValue)}  ${t(labels.timeValue)}';
    final hasGeo = proof.latitude != null && proof.longitude != null;
    final hasAddress =
        proof.address != null || proof.overlayAddressText != null;
    final refId = proofReferenceLabelFromProofId(proof.id);
    final hasNote =
        proof.description != null && proof.description!.isNotEmpty;
    final hasClient = labels.clientValue != '-';
    final hasSite = labels.siteMissionValue != '-';
    final showClientInPdf = hasClient && metadataMask.includeClient;
    final showSiteInPdf = hasSite && metadataMask.includeSite;
    final showNoteInPdf = hasNote && metadataMask.includeNote;

    final premium = appearance.reportStyle == PdfReportStyle.premium;

    // ----- V3 refined text styles (Premium = hiérarchie forte ; Standard = neutre et dense) -----
    final sBrand = pw.TextStyle(
      font: font,
      fontSize: premium ? 10.5 : 8.5,
      fontWeight: pw.FontWeight.bold,
      color: _bleuNuit,
      letterSpacing: premium ? 3.5 : 2,
    );
    final sTitle = pw.TextStyle(
      font: font,
      fontSize: premium ? 20 : 16,
      fontWeight: pw.FontWeight.bold,
      color: _bleuNuit,
    );
    final sSub = pw.TextStyle(
      font: font,
      fontSize: premium ? 9 : 8,
      color: _grisLabel,
    );
    final sSec = pw.TextStyle(
      font: font,
      fontSize: premium ? 8.5 : 8,
      fontWeight: pw.FontWeight.bold,
      color: premium ? _bleuNuit : _grisFonce,
      letterSpacing: premium ? 1.5 : 0.8,
    );
    final sLbl = pw.TextStyle(font: font, fontSize: 9, color: _grisLabel);
    final sVal = pw.TextStyle(
      font: font, fontSize: 9.5,
      fontWeight: pw.FontWeight.bold, color: _grisFonce,
    );
    final sBody = pw.TextStyle(font: font, fontSize: 9.5, color: _grisFonce);
    final sDiscrete = pw.TextStyle(font: font, fontSize: 8.5, color: _grisLabel);
    final sMeta = pw.TextStyle(font: font, fontSize: 7.5, color: _grisLabel);
    final sFtBrand = pw.TextStyle(
      font: font, fontSize: 8.5,
      fontWeight: pw.FontWeight.bold, color: _bleuNuit,
    );
    final sFtLabel = pw.TextStyle(font: font, fontSize: 8, color: _grisLabel);
    final sFtMeta = pw.TextStyle(font: font, fontSize: 7.5, color: _grisClair);
    final sFtLegal = pw.TextStyle(font: font, fontSize: 7, color: _grisClair);

    // ----- V3 reusable builders -----
    pw.Widget secTitle(String title) => premium
        ? pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(t(title).toUpperCase(), style: sSec),
              pw.SizedBox(height: 3),
              pw.Container(width: 28, height: 1.5, color: _bleuNuit),
            ],
          )
        : pw.Padding(
            padding: const pw.EdgeInsets.only(bottom: 2),
            child: pw.Text(t(title).toUpperCase(), style: sSec),
          );

    pw.Widget kv(String label, String value,
            {pw.TextStyle? vs, double lw = 110}) =>
        pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 4),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.SizedBox(
                width: lw,
                child: pw.Text(t(label), style: sLbl),
              ),
              pw.Expanded(
                child: pw.Text(t(value), style: vs ?? sVal),
              ),
            ],
          ),
        );

    pw.Widget thinLine() => pw.Container(
          width: double.infinity,
          height: 0.5,
          color: _separateur,
        );

    pw.Widget accentCard({required pw.Widget child}) => premium
        ? pw.Container(
            decoration: pw.BoxDecoration(
              color: _fondClair,
              border: pw.Border(
                left: pw.BorderSide(color: _bleuNuit, width: 2.5),
              ),
            ),
            padding:
                const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 8),
            child: child,
          )
        : pw.Container(
            decoration: pw.BoxDecoration(
              color: PdfColors.white,
              border: pw.Border.all(color: _separateur, width: 0.75),
            ),
            padding:
                const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 7),
            child: child,
          );

    pw.Widget framedPhoto(Uint8List bytes, {required double height}) =>
        pw.Container(
          decoration: pw.BoxDecoration(
            border: pw.Border.all(color: _separateur, width: 0.5),
          ),
          padding: const pw.EdgeInsets.all(3),
          child: pw.Image(
            pw.MemoryImage(bytes),
            height: height,
            fit: pw.BoxFit.contain,
          ),
        );

    final galleryRowH = premium ? 180.0 : 150.0;

    List<pw.Widget> galleryRows(List<Uint8List> photos) {
      final rows = <pw.Widget>[];
      for (var i = 0; i < photos.length; i += 2) {
        if (i > 0) rows.add(pw.SizedBox(height: premium ? 10 : 8));
        final hasSecond = i + 1 < photos.length;
        rows.add(
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Expanded(child: framedPhoto(photos[i], height: galleryRowH)),
              pw.SizedBox(width: 10),
              if (hasSecond)
                pw.Expanded(
                    child: framedPhoto(photos[i + 1], height: galleryRowH))
              else
                pw.Expanded(child: pw.SizedBox()),
            ],
          ),
        );
      }
      return rows;
    }

    // ----- Assemble document -----
    final doc = pw.Document(
      title: t(labels.docTitle),
      author: 'StampSight',
    );
    final pdfTheme = pw.ThemeData.withFont(
      base: font, bold: font, italic: font, boldItalic: font,
    );
    final imageBytes = png;

    final allPhotosFull = <Uint8List>[
      if (imageBytes != null) imageBytes,
      ...additionalPngs,
    ];
    final allPhotos = appearance.includeAllPhotos || allPhotosFull.isEmpty
        ? allPhotosFull
        : <Uint8List>[allPhotosFull.first];
    final totalPhotos = allPhotos.length;

    final singlePhotoH = premium ? 370.0 : 300.0;
    final pairPhotoH = premium ? 260.0 : 220.0;
    final heroMultiH = premium ? 280.0 : 230.0;

    doc.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(
          margin: pw.EdgeInsets.symmetric(
            horizontal: premium ? 36 : 32,
            vertical: premium ? 24 : 20,
          ),
          theme: pdfTheme,
        ),
        build: (context) => [
          // ===== HEADER V3 — iconique =====
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text(
                appearance.showBranding ? 'STAMPSIGHT' : '',
                style: sBrand,
              ),
              pw.Text(
                '${t(labels.referenceLabel)} $refId',
                style: sMeta,
              ),
            ],
          ),
          pw.SizedBox(height: premium ? 5 : 4),
          pw.Container(
            width: double.infinity,
            height: premium ? 2 : 1,
            color: _bleuNuit,
          ),
          pw.SizedBox(height: premium ? 12 : 8),
          pw.Text(t(labels.docTitle), style: sTitle),
          pw.SizedBox(height: 3),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(t(labels.subtitle), style: sSub),
              pw.Text(exportDate, style: sMeta),
            ],
          ),
          pw.SizedBox(height: 10),
          thinLine(),
          pw.SizedBox(height: 10),

          // ===== RÉSUMÉ DE PREUVE — grille raffinée =====
          secTitle(labels.proofSummaryTitle),
          pw.SizedBox(height: 8),
          accentCard(
            child: pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      kv(labels.typeLabel, labels.typeValue, lw: 85),
                      kv(labels.dateLabel, labels.dateValue, lw: 85),
                      kv(labels.timeLabel, labels.timeValue, lw: 85),
                    ],
                  ),
                ),
                pw.SizedBox(width: 12),
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      if (showClientInPdf)
                        kv(labels.clientLabel, labels.clientValue,
                            lw: 85),
                      if (showSiteInPdf)
                        kv(labels.siteMissionLabel,
                            labels.siteMissionValue,
                            lw: 85),
                      if (!showClientInPdf && !showSiteInPdf)
                        kv(labels.contextLabel, labels.contextValue,
                            lw: 85),
                    ],
                  ),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 10),
          thinLine(),
          pw.SizedBox(height: 10),

          // ===== PHOTOGRAPHIC EVIDENCE — adaptive layout =====
          secTitle(totalPhotos <= 1
              ? labels.photoSectionTitle
              : labels.photoSectionTitlePlural),
          pw.SizedBox(height: 4),
          if (totalPhotos > 1)
            pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 6),
              child: pw.Text(
                '$totalPhotos photos',
                style: sDiscrete,
              ),
            ),
          // CAS 1 — single photo: full-width hero
          if (totalPhotos == 1)
            pw.Center(child: framedPhoto(allPhotos[0], height: singlePhotoH)),
          // CAS 2 — two photos: balanced side-by-side
          if (totalPhotos == 2)
            pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Expanded(
                    child: framedPhoto(allPhotos[0], height: pairPhotoH)),
                pw.SizedBox(width: 10),
                pw.Expanded(
                    child: framedPhoto(allPhotos[1], height: pairPhotoH)),
              ],
            ),
          // CAS 3+ — hero principal + galerie uniforme
          if (totalPhotos >= 3) ...[
            pw.Center(child: framedPhoto(allPhotos[0], height: heroMultiH)),
            pw.SizedBox(height: 10),
            ...galleryRows(allPhotos.sublist(1)),
          ],
          pw.SizedBox(height: 10),

          // ===== OBSERVATIONS — pull-quote =====
          if (showNoteInPdf) ...[
            secTitle(labels.observationsTitle),
            pw.SizedBox(height: 6),
            pw.Container(
              decoration: pw.BoxDecoration(
                border: pw.Border(
                  left: pw.BorderSide(color: _grisLabel, width: 2),
                ),
              ),
              padding:
                  const pw.EdgeInsets.only(left: 10, top: 2, bottom: 2),
              child: pw.Text(t(labels.noteValue), style: sBody),
            ),
            pw.SizedBox(height: 8),
          ],
          thinLine(),
          pw.SizedBox(height: 8),

          // ===== TRAÇABILITÉ — localisation détaillée ou synthétique =====
          secTitle(labels.traceabilityTitle),
          pw.SizedBox(height: 6),
          if (appearance.showDetailedLocation)
            accentCard(
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  kv(labels.addressLabel, labels.addressValue, lw: 140),
                  kv(labels.coordinatesLabel, labels.coordinatesValue,
                      vs: sDiscrete, lw: 140),
                  kv(labels.capturedOnLabel, capturedDate, lw: 140),
                  kv(labels.exportedOnLabel, exportDate, lw: 140),
                  kv(labels.sourceLabel, labels.sourceValue, lw: 140),
                  pw.Padding(
                    padding: const pw.EdgeInsets.only(top: 2),
                    child: pw.Row(
                      children: [
                        pw.Text(
                          '${t(labels.geoRecordedLabel)} : '
                          '${t(hasGeo ? labels.yesText : labels.noText)}',
                          style: sDiscrete,
                        ),
                        pw.SizedBox(width: 18),
                        pw.Text(
                          '${t(labels.addressResolvedLabel)} : '
                          '${t(hasAddress ? labels.yesText : labels.noText)}',
                          style: sDiscrete,
                        ),
                      ],
                    ),
                  ),
                  pw.SizedBox(height: 2),
                  kv(labels.referenceLabel, refId, lw: 140),
                ],
              ),
            )
          else
            accentCard(
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  kv(labels.capturedOnLabel, capturedDate, lw: 140),
                  kv(labels.exportedOnLabel, exportDate, lw: 140),
                  kv(labels.referenceLabel, refId, lw: 140),
                  kv(labels.sourceLabel, labels.sourceValue, lw: 140),
                ],
              ),
            ),
          pw.SizedBox(height: 10),

          // ===== SYNTHÈSE DOCUMENT (bas de page utile) =====
          if (appearance.showCredibilityBlock) ...[
            secTitle(labels.documentSummaryTitle),
            pw.SizedBox(height: 6),
            accentCard(
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  kv(labels.photosInExportLabel, '$totalPhotos', lw: 140),
                  if (showClientInPdf || showSiteInPdf)
                    kv(
                      labels.contextLabel,
                      showClientInPdf && showSiteInPdf
                          ? '${t(labels.clientValue)} — ${t(labels.siteMissionValue)}'
                          : showClientInPdf
                              ? t(labels.clientValue)
                              : t(labels.siteMissionValue),
                      lw: 140,
                    ),
                  kv(labels.referenceLabel, refId, lw: 140),
                  kv(labels.sourceLabel, t(labels.sourceValue), lw: 140),
                  pw.SizedBox(height: 6),
                  pw.Text(t(labels.dataIncludedDescription), style: sBody),
                  pw.SizedBox(height: 6),
                  pw.Text(t(labels.documentScopeNote), style: sDiscrete),
                ],
              ),
            ),
            pw.SizedBox(height: 10),
          ],

          // ===== FOOTER V3 — signature compacte =====
          pw.Container(
            width: double.infinity, height: 1.5, color: _bleuNuit,
          ),
          pw.SizedBox(height: 5),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                appearance.showBranding ? 'StampSight' : '',
                style: sFtBrand,
              ),
              pw.Text(t(labels.fieldProofDocText), style: sFtLabel),
            ],
          ),
          pw.SizedBox(height: 2),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(exportDate, style: sFtMeta),
              pw.Text(
                '${t(labels.referenceLabel)} $refId',
                style: sFtMeta,
              ),
            ],
          ),
          pw.SizedBox(height: 3),
          if (appearance.showCredibilityBlock)
            pw.Text(t(labels.autoGeneratedText), style: sFtLegal),
        ],
      ),
    );

    try {
      return await doc.save();
    } catch (e, stack) {
      Error.throwWithStackTrace(StateError('PDF save failed: $e'), stack);
    }
  }

  static Future<File> writePdfToTemp(
    Proof proof,
    ProofPdfLabels labels, {
    PdfAppearancePreferences appearance = PdfAppearancePreferences.defaults,
    PdfMetadataExportMask metadataMask = PdfMetadataExportMask.all,
  }) {
    final cacheKey =
        '${proof.id}_${appearance.showBranding}_${appearance.showCredibilityBlock}_${appearance.showDetailedLocation}_${appearance.includeAllPhotos}_${appearance.reportStyle.name}_${metadataMask.includeClient}_${metadataMask.includeSite}_${metadataMask.includeNote}';
    return _writePdfTempInFlight.putIfAbsent(cacheKey, () async {
      try {
        final bytes = await buildPdfBytes(
          proof,
          labels,
          appearance: appearance,
          metadataMask: metadataMask,
        );
        final dir = await getTemporaryDirectory();
        final file = File('${dir.path}/stampsight_${proof.id}.pdf');
        await file.writeAsBytes(bytes);
        return file;
      } finally {
        Future.microtask(() {
          _writePdfTempInFlight.remove(cacheKey);
        });
      }
    });
  }

  // ---------------------------------------------------------------------------
  // Grouped PDF — multi-proof report
  // ---------------------------------------------------------------------------
  static bool _groupedPdfInFlight = false;

  static Future<File> writeGroupedPdfToTemp({
    required List<Proof> proofs,
    required List<ProofPdfLabels> labelsList,
    required AppLocalizations l10n,
    PdfAppearancePreferences appearance = PdfAppearancePreferences.defaults,
    PdfMetadataExportMask metadataMask = PdfMetadataExportMask.all,
  }) async {
    if (_groupedPdfInFlight) {
      throw StateError('Grouped PDF generation already in progress');
    }
    _groupedPdfInFlight = true;
    try {
      final bytes = await buildGroupedPdfBytes(
        proofs: proofs,
        labelsList: labelsList,
        l10n: l10n,
        appearance: appearance,
        metadataMask: metadataMask,
      );
      final dir = await getTemporaryDirectory();
      final ts = DateTime.now().millisecondsSinceEpoch;
      final file = File('${dir.path}/stampsight_grouped_$ts.pdf');
      await file.writeAsBytes(bytes);
      return file;
    } finally {
      _groupedPdfInFlight = false;
    }
  }

  static const int _groupedImageMaxDim = 600;

  static img.Image _resizeForGrouped(img.Image src) {
    if (src.width <= _groupedImageMaxDim &&
        src.height <= _groupedImageMaxDim) {
      return src;
    }
    final landscape = src.width >= src.height;
    return img.copyResize(
      src,
      width: landscape ? _groupedImageMaxDim : null,
      height: landscape ? null : _groupedImageMaxDim,
      interpolation: img.Interpolation.average,
    );
  }

  static Future<Uint8List?> _loadImageForGrouped(String filePath) async {
    try {
      final f = File(filePath);
      if (!f.existsSync()) return null;
      final bytes = await f.readAsBytes();
      final decoded = img.decodeImage(bytes);
      if (decoded == null) return null;
      final resized = _resizeForGrouped(decoded);
      return Uint8List.fromList(img.encodePng(resized));
    } catch (_) {
      return null;
    }
  }

  static Future<Uint8List> buildGroupedPdfBytes({
    required List<Proof> proofs,
    required List<ProofPdfLabels> labelsList,
    required AppLocalizations l10n,
    PdfAppearancePreferences appearance = PdfAppearancePreferences.defaults,
    PdfMetadataExportMask metadataMask = PdfMetadataExportMask.all,
  }) async {
    final font = await _loadPdfUnicodeFont();
    String t(String s) => _pdfSafeText(s);

    final now = DateTime.now();
    final exportDate = _fmtDt(now);
    final premium = appearance.reportStyle == PdfReportStyle.premium;

    // Styles
    final sBrand = pw.TextStyle(
      font: font,
      fontSize: premium ? 10.5 : 8.5,
      fontWeight: pw.FontWeight.bold,
      color: _bleuNuit,
      letterSpacing: premium ? 3.5 : 2,
    );
    final sCoverTitle = pw.TextStyle(
      font: font,
      fontSize: premium ? 22 : 18,
      fontWeight: pw.FontWeight.bold,
      color: _bleuNuit,
    );
    final sCoverSub = pw.TextStyle(
      font: font,
      fontSize: premium ? 10 : 9,
      color: _grisLabel,
    );
    final sSec = pw.TextStyle(
      font: font,
      fontSize: premium ? 8.5 : 8,
      fontWeight: pw.FontWeight.bold,
      color: premium ? _bleuNuit : _grisFonce,
      letterSpacing: premium ? 1.5 : 0.8,
    );
    final sLbl = pw.TextStyle(font: font, fontSize: 9, color: _grisLabel);
    final sVal = pw.TextStyle(
      font: font, fontSize: 9.5,
      fontWeight: pw.FontWeight.bold, color: _grisFonce,
    );
    final sBody = pw.TextStyle(font: font, fontSize: 9.5, color: _grisFonce);
    final sDiscrete = pw.TextStyle(
      font: font, fontSize: 8.5, color: _grisLabel,
    );
    final sMeta = pw.TextStyle(font: font, fontSize: 7.5, color: _grisLabel);
    final sFtBrand = pw.TextStyle(
      font: font, fontSize: 8.5,
      fontWeight: pw.FontWeight.bold, color: _bleuNuit,
    );
    final sFtMeta = pw.TextStyle(font: font, fontSize: 7.5, color: _grisClair);
    final sFtLegal = pw.TextStyle(font: font, fontSize: 7, color: _grisClair);

    pw.Widget thinLine() => pw.Container(
          width: double.infinity, height: 0.5, color: _separateur,
        );

    pw.Widget kv(String label, String value,
            {pw.TextStyle? vs, double lw = 120}) =>
        pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 3),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.SizedBox(width: lw, child: pw.Text(t(label), style: sLbl)),
              pw.Expanded(child: pw.Text(t(value), style: vs ?? sVal)),
            ],
          ),
        );

    pw.Widget accentCard({required pw.Widget child}) => premium
        ? pw.Container(
            decoration: pw.BoxDecoration(
              color: _fondClair,
              border: pw.Border(
                left: pw.BorderSide(color: _bleuNuit, width: 2.5),
              ),
            ),
            padding:
                const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 8),
            child: child,
          )
        : pw.Container(
            decoration: pw.BoxDecoration(
              color: PdfColors.white,
              border: pw.Border.all(color: _separateur, width: 0.75),
            ),
            padding:
                const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 7),
            child: child,
          );

    pw.Widget secTitle(String title) => premium
        ? pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(t(title).toUpperCase(), style: sSec),
              pw.SizedBox(height: 3),
              pw.Container(width: 28, height: 1.5, color: _bleuNuit),
            ],
          )
        : pw.Padding(
            padding: const pw.EdgeInsets.only(bottom: 2),
            child: pw.Text(t(title).toUpperCase(), style: sSec),
          );

    // Build document
    final doc = pw.Document(
      title: t(l10n.pdfGroupedCoverTitle),
      author: 'StampSight',
    );
    final pdfTheme = pw.ThemeData.withFont(
      base: font, bold: font, italic: font, boldItalic: font,
    );

    // Cover page widgets
    final coverWidgets = <pw.Widget>[
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        crossAxisAlignment: pw.CrossAxisAlignment.end,
        children: [
          pw.Text(
            appearance.showBranding ? 'STAMPSIGHT' : '',
            style: sBrand,
          ),
          pw.Text(exportDate, style: sMeta),
        ],
      ),
      pw.SizedBox(height: premium ? 5 : 4),
      pw.Container(
        width: double.infinity,
        height: premium ? 2 : 1,
        color: _bleuNuit,
      ),
      pw.SizedBox(height: premium ? 20 : 14),
      pw.Text(t(l10n.pdfGroupedCoverTitle), style: sCoverTitle),
      pw.SizedBox(height: 4),
      pw.Text(t(l10n.pdfGroupedCoverSubtitle), style: sCoverSub),
      pw.SizedBox(height: 16),
      thinLine(),
      pw.SizedBox(height: 12),
      accentCard(
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            kv(l10n.pdfGroupedProofsIncluded, '${proofs.length}'),
            kv(l10n.pdfGroupedExportDate, exportDate),
          ],
        ),
      ),
      pw.SizedBox(height: 16),
      thinLine(),
      pw.SizedBox(height: 16),
    ];

    pw.Widget framedGroupedShot(Uint8List bytes, double h) => pw.Container(
          decoration: pw.BoxDecoration(
            border: pw.Border.all(color: _separateur, width: 0.5),
          ),
          padding: const pw.EdgeInsets.all(2),
          child: pw.Image(
            pw.MemoryImage(bytes),
            height: h,
            fit: pw.BoxFit.contain,
          ),
        );

    // Each proof section
    final proofSections = <pw.Widget>[];
    for (var i = 0; i < proofs.length; i++) {
      final proof = proofs[i];
      final labels = labelsList[i];
      final hasNote =
          proof.description != null && proof.description!.isNotEmpty;
      final refId = proofReferenceLabelFromProofId(proof.id);
      final capturedDate = '${t(labels.dateValue)}  ${t(labels.timeValue)}';

      Uint8List? mainPng;
      if (proof.refersToLocalImageFile) {
        mainPng = await _loadImageForGrouped(proof.imagePath);
      }
      if (mainPng == null) {
        for (final path in [
          ProofCategoryAsset.placeholderFor(proof.proofType),
          ProofCategoryAsset.homeMirrorFor(proof.proofType),
        ]) {
          mainPng = await _assetAsPngBytes(path);
          if (mainPng != null) break;
        }
      }

      final sectionImages = <Uint8List>[];
      if (mainPng != null) sectionImages.add(mainPng);
      if (appearance.includeAllPhotos) {
        for (final extraPath in proof.additionalImagePaths) {
          final ex = await _loadImageForGrouped(extraPath);
          if (ex != null) sectionImages.add(ex);
        }
      }

      final hasClient = labels.clientValue != '-';
      final hasSite = labels.siteMissionValue != '-';
      final showClientInPdf = hasClient && metadataMask.includeClient;
      final showSiteInPdf = hasSite && metadataMask.includeSite;
      final showNoteInPdf = hasNote && metadataMask.includeNote;

      final titleStyle = pw.TextStyle(
        font: font,
        fontSize: premium ? 14 : 12,
        fontWeight: pw.FontWeight.bold,
        color: _bleuNuit,
      );
      final mainImgH = premium ? 240.0 : 200.0;
      final pairH = premium ? 200.0 : 170.0;
      final thumbH = 120.0;

      final imageWidgets = <pw.Widget>[];
      if (sectionImages.length == 1) {
        imageWidgets.add(pw.Center(child: framedGroupedShot(sectionImages[0], mainImgH)));
      } else if (sectionImages.length == 2) {
        imageWidgets.add(
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Expanded(child: framedGroupedShot(sectionImages[0], pairH)),
              pw.SizedBox(width: 8),
              pw.Expanded(child: framedGroupedShot(sectionImages[1], pairH)),
            ],
          ),
        );
      } else if (sectionImages.length >= 3) {
        imageWidgets.add(
          pw.Center(child: framedGroupedShot(sectionImages[0], mainImgH * 0.92)),
        );
        imageWidgets.add(pw.SizedBox(height: 8));
        for (var j = 1; j < sectionImages.length; j += 2) {
          final hasSecond = j + 1 < sectionImages.length;
          imageWidgets.add(
            pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Expanded(child: framedGroupedShot(sectionImages[j], thumbH)),
                pw.SizedBox(width: 8),
                if (hasSecond)
                  pw.Expanded(
                      child: framedGroupedShot(sectionImages[j + 1], thumbH))
                else
                  pw.Expanded(child: pw.SizedBox()),
              ],
            ),
          );
          if (j + 2 < sectionImages.length) {
            imageWidgets.add(pw.SizedBox(height: 6));
          }
        }
      }

      proofSections.addAll([
        secTitle('${l10n.pdfGroupedProofSection} ${i + 1} / ${proofs.length}'),
        pw.SizedBox(height: 6),
        pw.Text(t(labels.docTitle), style: titleStyle),
        pw.SizedBox(height: 4),
        pw.Text('$refId  -  $capturedDate', style: sDiscrete),
        pw.SizedBox(height: 8),
        ...imageWidgets,
        pw.SizedBox(height: 6),
        accentCard(
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              kv(labels.typeLabel, labels.typeValue),
              if (appearance.showDetailedLocation) ...[
                kv(labels.addressLabel, labels.addressValue),
                kv(labels.coordinatesLabel, labels.coordinatesValue,
                    vs: sDiscrete),
              ],
              if (showClientInPdf)
                kv(labels.clientLabel, labels.clientValue),
              if (showSiteInPdf)
                kv(labels.siteMissionLabel, labels.siteMissionValue),
            ],
          ),
        ),
        if (showNoteInPdf) ...[
          pw.SizedBox(height: 4),
          pw.Container(
            decoration: pw.BoxDecoration(
              border: pw.Border(
                left: pw.BorderSide(color: _grisLabel, width: 2),
              ),
            ),
            padding:
                const pw.EdgeInsets.only(left: 10, top: 2, bottom: 2),
            child: pw.Text(t(labels.noteValue), style: sBody),
          ),
        ],
        pw.SizedBox(height: 12),
        if (i < proofs.length - 1) ...[
          thinLine(),
          pw.SizedBox(height: 12),
        ],
      ]);
    }

    final totalPhotographs = proofs.fold<int>(
      0,
      (sum, p) =>
          sum +
          (appearance.includeAllPhotos ? p.totalImageCount : 1),
    );

    // Synthèse avant pied de page
    final closingWidgets = <pw.Widget>[
      if (appearance.showCredibilityBlock) ...[
        secTitle(l10n.pdfGroupedClosingTitle),
        pw.SizedBox(height: 6),
        accentCard(
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              kv(l10n.pdfGroupedTotalPhotographs, '$totalPhotographs'),
              pw.SizedBox(height: 6),
              pw.Text(t(l10n.pdfDataIncludedDescription), style: sBody),
              pw.SizedBox(height: 6),
              pw.Text(t(l10n.pdfDocumentScopeNote), style: sDiscrete),
            ],
          ),
        ),
        pw.SizedBox(height: 10),
      ],
    ];

    // Footer widgets
    final footerWidgets = <pw.Widget>[
      pw.Container(width: double.infinity, height: 1.5, color: _bleuNuit),
      pw.SizedBox(height: 5),
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            appearance.showBranding ? 'StampSight' : '',
            style: sFtBrand,
          ),
          pw.Text(t(l10n.pdfGroupedCoverTitle), style: sFtMeta),
        ],
      ),
      pw.SizedBox(height: 2),
      pw.Text(exportDate, style: sFtMeta),
      if (appearance.showCredibilityBlock) ...[
        pw.SizedBox(height: 3),
        pw.Text(t(l10n.pdfAutoGenerated), style: sFtLegal),
      ],
    ];

    doc.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(
          margin: pw.EdgeInsets.symmetric(
            horizontal: premium ? 36 : 32,
            vertical: premium ? 24 : 20,
          ),
          theme: pdfTheme,
        ),
        build: (context) => [
          ...coverWidgets,
          ...proofSections,
          ...closingWidgets,
          ...footerWidgets,
        ],
      ),
    );

    try {
      return await doc.save();
    } catch (e, stack) {
      Error.throwWithStackTrace(
          StateError('Grouped PDF save failed: $e'), stack);
    }
  }
}
